version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'staging'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'upgrade-next-intl'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7