image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install
    init: |
      pnpm install
      pnpm recursive install --filter ./web --filter ./legacy/css --filter ./legacy/js
      gp sync-done install
    command: pnpm web dev
  - name: Storybook
    init: gp sync-await install
    command: pnpm web storybook
    openMode: split-right
  - name: Lint
    init: gp sync-await install
    command: pnpm lint:web
    openMode: split-right
  - name: Test
    init: gp sync-await install
    command: pnpm web test
    openMode: split-right

ports:
  - port: 3000
    onOpen: open-preview
  - port: 9000
    onOpen: ignore

gitConfig:
  alias.co: checkout
  alias.br: branch
  alias.ci: commit
  alias.st: status
  pull.rebase: merges

vscode:
  extensions:
    - vtrois.gitmoji-vscode
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - pflannery.vscode-versionlens
    - jpoissonnier.vscode-styled-components
    - jock.svg
    - digitalbrainstem.javascript-ejs-support
