packages:
  - 'web'
  - 'e2e'
  - 'sanityv3'
  - 'search'
overrides:
  'tar-fs': '^3.0.9'
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - axios@1.15.1 # Fix axios CVE-2026-40175, checked release is built and signed with provenance
#trustPolicy: 'no-downgrade'
blockExoticSubdeps: true
