packages:
  - 'web'
  - 'studio'
  - 'search'
  - 'packages/energyvision'
  - 'packages/typescript-config'
minimumReleaseAge: 10080
# Ignore trust policy assuming they are safe due to their age
trustPolicyIgnoreAfter: 10080
blockExoticSubdeps: true
trustPolicyExclude:
  # https://github.com/reduxjs/reselect/issues/752
  # might apply for @reduxjs/toolkit@2.9.2 by recharts@3.8.1
  - reselect@5.1.1
allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: false
overrides:
  tar: 7.5.19
  vite: 7.3.5
  basic-ftp: 5.3.1
  '@xmldom/xmldom': 0.8.13
  '@sanity/types': 6.7.0
publicHoistPattern:
  - '*import-in-the-middle*'
  - '*require-in-the-middle*'
minimumReleaseAgeExclude:
  - '@next/env@16.3.3'
  - '@next/swc-darwin-arm64@16.3.3'
  - '@next/swc-darwin-x64@16.3.3'
  - '@next/swc-linux-arm64-gnu@16.3.3'
  - '@next/swc-linux-arm64-musl@16.3.3'
  - '@next/swc-linux-x64-gnu@16.3.3'
  - '@next/swc-linux-x64-musl@16.3.3'
  - '@next/swc-win32-arm64-msvc@16.3.3'
  - '@next/swc-win32-x64-msvc@16.3.3'
  - next@16.3.3
