export { default as Facebook } from './Facebook'
export { default as Instagram } from './Instagram'
export { default as Linkedin } from './Linkedin'
export { default as Twitter } from './Twitter'
export { default as Youtube } from './Youtube'
export { default as ArrowRight } from './ArrowRight'
export { default as Play } from './Play'
export { default as Pause } from './Pause'
