name: 'Deploy web'
description: 'Steps needed to deploy all websites to Radix'
inputs:
  imageName:
    description: 'The path to where the image is to be copied'
    required: true
  commitSha:
    description: 'sha of image to be used'
    required: false
  projectId:
    description: 'Id of the sanity project'
    required: false
  datasetName:
    description: 'Name of dataset to be used for Sanity'
    required: true
  githubToken:
    description: 'GitHub token'
    required: true
  sanityApiToken:
    description: 'Sanity API token'
    required: true
  algoliaAppId:
    description: 'AppID for Algolia'
    required: true
  environment:
    description: 'dev, preprod or prod'
    required: true
  nodeEnvironment:
    description: 'development or production'
    required: true
  algoliaApiKey:
    description: 'Api key for Algolia'
    required: false
  archiveContentLink:
    description: 'Archive storage link'
    required: true
  friendlyCaptchaSitekey:
    description: 'Friendly captcha site key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Force JS Actions Node 24
      shell: bash
      run: |
        echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV
    - name: Checkout 🛎 ️
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Get long sha ️🏷️
      if: "${{ inputs.commitSha != '' }}"
      id: get-long-sha
      shell: bash
      run: |
        echo "sha=$(git rev-parse ${{ inputs.commitSha }})" >> $GITHUB_OUTPUT
    - name: Checkout specific branch 🛎️
      if: "${{ inputs.commitSha != '' }}"
      id: checkout-specific-branch
      uses: actions/checkout@v6
      with:
        repository: 'equinor/energyvision'
        fetch-depth: 0
        ref: '${{ steps.get-long-sha.outputs.sha }}'
    - name: Set default image tag 🏷
      if: "${{ inputs.commitSha == '' }}"
      shell: bash
      id: set-default-image-tag
      run: |
        echo "IMAGE_TAG=$(echo ${GITHUB_REF##*/}-latest)" >> $GITHUB_ENV
        echo "IMAGE_TAG_SHA=$(git rev-parse --short=12 ${GITHUB_SHA})" >> $GITHUB_ENV
    - name: Set image tags based on commit sha 🏷
      if: "${{ inputs.commitSha != '' }}"
      shell: bash
      id: set-image-tag
      run: |
        echo "IMAGE_TAG=${{inputs.commitSha}}" >> $GITHUB_ENV
        echo "IMAGE_TAG_SHA=${{inputs.commitSha}}" >> $GITHUB_ENV
    - name: Set up Docker Buildx 🔧
      uses: docker/setup-buildx-action@v4
    - name: Login to GHCR 🔐
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.githubToken }}
    
    - name: Build web component ⚙️
      id: build
      uses: docker/build-push-action@v7
      with:
        context: .
        file: web/Dockerfile
        push: true
        tags: |
          ghcr.io/equinor/energyvision/web-${{ inputs.datasetName }}-upgrade:${{ env.IMAGE_TAG }}
          ghcr.io/equinor/energyvision/web-${{ inputs.datasetName }}-upgrade:${{ env.IMAGE_TAG_SHA }}
        cache-from: type=registry,ref=${{ inputs.imageName }}:${{ env.IMAGE_TAG }}
        #cache-from: type=registry,ref=ghcr.io/equinor/energyvision/web-${{ inputs.datasetName }}-upgrade:${{ env.IMAGE_TAG }}
        cache-to: type=inline
        secrets: |
          sanity_api_token=${{ inputs.sanityApiToken }}
          next_public_algolia_search_api_key=${{ inputs.algoliaApiKey }}
        build-args: |
          ARG_SANITY_PROJECT_ID=${{ inputs.projectId }}
          ARG_SANITY_DATASET=${{ inputs.datasetName }}
          ARG_ALGOLIA_APP_ID=${{ inputs.algoliaAppId }}
          ARG_ENV=${{ inputs.environment }}
          ARG_NODE_ENV=${{ inputs.nodeEnvironment }}
          ARG_ARCHIVE_CONTENT_LINK=${{ inputs.archiveContentLink }}
          ARG_FRIENDLY_CAPTCHA_SITEKEY=${{ inputs.friendlyCaptchaSitekey }}
   
    - name: Get component name
      id: get-component-name
      shell: bash
      run: |
        component=${{ inputs.datasetName == 'global' && 'web-upgrade' || format('{0}{1}{2}', 'web-', inputs.datasetName,'-upgrade') }}
        echo "Component name is $component"
        echo "COMPONENT_NAME=$component" >> $GITHUB_ENV
   # MAIN CLUSTER
    - name: Deploy to Radix c2 🚀
      id: deploy-c2
      uses: equinor/radix-github-actions@v2
      with:
        azure_client_id: 460b889f-89e0-4cc9-965c-31f3e7770226
        version: latest

    - run: rx create job deploy
        --component $COMPONENT_NAME
        --context platform2
        -a equinor-web-sites
        -e ${{ inputs.environment }}
        -f
      shell: bash

    - name: log-errors-to-slack 📄
      uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: failure()
