name: 'Deploy studio'
description: 'Steps needed to deploy a studio to Radix'
inputs:
  imageName:
    description: 'The path to where the image is to be copied'
    required: true
  commitSha:
    description: 'sha of image to be used'
    required: false
  datasetName:
    description: 'Name of dataset to be used for Sanity'
    required: true
  githubToken:
    description: 'GitHub token'
    required: true
  sanityPreviewToken:
    description: 'Sanity Preview token'
    required: true
  brandmasterUrl:
    description: 'Sanity Studio Brandmaster Url'
    required: true
  brandmasterPluginSource:
    description: 'Sanity Studio Brandmaster Plugin Source'
    required: true
  fotowareClientId:
    description: 'Client ID for Fotoware integration'
    required: true
  fotowareTenantUrl:
    description: 'Tenant URL for Fotoware application'
    required: true
  fotowareRedirectOrigin:
    description: 'Redirect Origin for Fotoware auth'
    required: true
  fotowareRedirectUri:
    description: 'Redirect URI for Fotoware auth'
    required: true
  fotowareAfExportUrl:
    description: 'Azure Function img export URL'
    required: true
  fotowareAfExportKey:
    description: 'Azure Function img export function key'
    required: true
  environment:
    description: 'dev, preprod or prod'
    required: true
  sanityApiToken:
    description: 'Sanity API token'
    required: true
  screen9accountId:
    description: 'Screen 9 Account Id'
    required: true
  screen9token:
    description: 'Screen9 API token'
    required: true
  previewUrl:
    description: 'Preview url for presentation'


runs:
  using: 'composite'
  steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get long sha ️🏷️
      if: "${{ inputs.commitSha != '' }}"
      id: get-long-sha
      shell: bash
      run: |
        echo "sha=$(git rev-parse ${{ inputs.commitSha }})" >> $GITHUB_OUTPUT
    - name: Checkout specific branch 🛎️
      if: "${{ inputs.commitSha != '' }}"
      id: checkout-specific-branch
      uses: actions/checkout@v4
      with:
        repository: 'equinor/energyvision'
        fetch-depth: 0
        ref: '${{ steps.get-long-sha.outputs.sha }}'
    - name: Set default image tag 🏷
      if: "${{ inputs.commitSha == '' }}"
      id: set-default-image-tag
      shell: bash
      run: |
        echo "IMAGE_TAG=$(echo ${GITHUB_REF##*/}-latest)" >> $GITHUB_ENV
        echo "IMAGE_TAG_SHA=$(git rev-parse --short=12 ${GITHUB_SHA})" >> $GITHUB_ENV
    - name: Set image tags based on commit sha 🏷
      if: "${{ inputs.commitSha != '' }}"
      shell: bash
      id: set-image-tag
      run: |
        echo "IMAGE_TAG=${{inputs.commitSha}}" >> $GITHUB_ENV
        echo "IMAGE_TAG_SHA=${{inputs.commitSha}}" >> $GITHUB_ENV
    - name: Set up Docker Buildx 🔧
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR 🔐
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.githubToken }}
    - name: Build sanity container ⚙️
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: studio/Dockerfile
        push: true
        tags: |
          ${{ inputs.imageName }}:${{ env.IMAGE_TAG }}
          ${{ inputs.imageName }}:${{ env.IMAGE_TAG_SHA }}
        cache-from: type=registry,ref=${{ inputs.imageName }}:${{ env.IMAGE_TAG }}
        cache-to: type=inline
        secrets: |
          sanity_studio_preview_secret=${{ inputs.sanityPreviewToken }}
          fotoware_af_export_key=${{ inputs.fotowareAfExportKey }}
          screen9_token=${{ inputs.screen9token }}
          sanity_api_token=${{ inputs.sanityApiToken }}
        build-args: |
          ARG_SANITY_DATASET=${{ inputs.datasetName }}
          ARG_BRANDMASTER_URL=${{ inputs.brandmasterUrl }}
          ARG_BRANDMASTER_PLUGIN=${{ inputs.brandmasterPluginSource }}
          ARG_FOTOWARE_CLIENT_ID=${{ inputs.fotowareClientId }}
          ARG_FOTOWARE_TENANT_URL=${{ inputs.fotowareTenantUrl }}
          ARG_FOTOWARE_REDIRECT_ORIGIN=${{ inputs.fotowareRedirectOrigin }}
          ARG_FOTOWARE_REDIRECT_URI=${{ inputs.fotowareRedirectUri }}
          ARG_FOTOWARE_AF_EXPORT_URL=${{ inputs.fotowareAfExportUrl }}
          ARG_FOTOWARE_AF_EXPORT_KEY=${{ inputs.fotowareAfExportKey }}
          ARG_SCREEN9_ACCOUNT_ID=${{ inputs.screen9accountId }}
          ARG_SANITY_STUDIO_PREVIEW_URL=${{ inputs.previewUrl }}
    - name: Get component name
      id: get-component-name
      shell: bash
      run: |
        component=${{ format('{0}{1}{2}', 'studio-', inputs.datasetName,'-upgrade') }}
        echo "Component name is $component"
        echo "COMPONENT_NAME=$component" >> $GITHUB_ENV
      # MAIN CLUSTER
    - name: Deploy to Radix c2 🚀
      id: deploy-c2
      uses: equinor/radix-github-actions@v2
      with:
        azure_client_id: 460b889f-89e0-4cc9-965c-31f3e7770226
        version: latest
    - run: rx create job deploy
        --context platform2
        --component $COMPONENT_NAME
        -a equinor-web-sites
        -e ${{ inputs.environment }}
        -f
      shell: bash
    - name: log-errors-to-slack 📄
      uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: failure()
