name: UPGRADE DEV - Build & deploy studio
on:
  workflow_dispatch:
  push:
    branches:
      - upgrade-next-intl
    paths:
      - 'studio/**/*'
      - './FeatureFlags.js'
      - '!./README.md'
      - '!./.env.development.template'
      - '!./studio/scripts/**/*'
permissions:
  id-token: write
  packages: write
jobs:
  check-code:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: staging
      - name: Install pnpm 📦
        id: install-pnpm
        uses: pnpm/action-setup@v4
      - name: Cache pnpm modules 💾
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies 🔧
        id: install-dependencies
        run: |
          pnpm install
          pnpm studio install
      - name: Run ESLint 🔎
        id: lint
        run: |
          pnpm lint:studio
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  deploy-studio:
    needs: check-code
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://studio-global-development-upgrade-energyvision-dev.radix.equinor.com/
    strategy:
      matrix:
        dataset: [global-development]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - id: deploy-satellite
        uses: ./.github/workflows/deploy-studio/
        with:
          imageName: ghcr.io/equinor/energyvision/studio-${{ matrix.dataset }}-upgrade
          datasetName: ${{ matrix.dataset }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          sanityApiToken: ${{ secrets.SANITY_API_TOKEN }}
          sanityHistoryApiToken: ${{ secrets.SANITY_STUDIO_HISTORY_API_TOKEN }}
          sanityPreviewToken: ${{ secrets.SANITY_STUDIO_PREVIEW_SECRET }}
          brandmasterUrl: ${{ secrets.SANITY_STUDIO_BRANDMASTER_URL }}
          brandmasterPluginSource: ${{ secrets.SANITY_STUDIO_BRANDMASTER_PLUGIN_SOURCE }}
          fotowareClientId: ${{ secrets.SANITY_STUDIO_FOTOWARE_CLIENT_ID }}
          fotowareTenantUrl: ${{ secrets.SANITY_STUDIO_FOTOWARE_TENANT_URL }}
          fotowareRedirectOrigin: ${{ secrets.SANITY_STUDIO_FOTOWARE_REDIRECT_ORIGIN }}
          fotowareAfExportUrl: ${{ secrets.SANITY_STUDIO_FOTOWARE_AF_EXPORT_URL }}
          fotowareAfExportKey: ${{ secrets.SANITY_STUDIO_FOTOWARE_AF_EXPORT_KEY }}
          screen9accountId: ${{ secrets.SANITY_STUDIO_SCREEN9_ACCOUNT_ID }}
          screen9token: ${{ secrets.SANITY_STUDIO_SCREEN9_TOKEN }}
          environment: ${{ secrets.ENV }}
          previewUrl: ${{ vars.SANITY_STUDIO_PREVIEW_URL}}

      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
