name: UPGRADE DEV - Build & Deploy equinor.com
on:
  workflow_dispatch:
  push:
    branches:
      - upgrade-next-intl
    paths:
      - 'web/**'
      - '!web/README.md'
      - '!web/.gitignore'
      - '!web/jest.config.cjs'
      - '!web/jest.setup.ts'
      - './FeatureFlags.js'
      - '!web/components/README.md'
  repository_dispatch:
    types: [sanity_publish]
permissions:
  id-token: write
  packages: write
jobs:
  deploy-global-development:
    needs: check-code
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://web-global-development-upgrade-equinor-web-sites-dev.c2.radix.equinor.com/
    strategy:
      # The matrix approach is needed to re-use code created for satellites
      matrix:
        dataset: ['global-development']
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - id: deploy-global-development
        uses: ./.github/workflows/deploy-web/
        with:
          imageName: ghcr.io/equinor/energyvision/web-${{ matrix.dataset }}-upgrade
          projectId: h61q9gi9
          datasetName: ${{ matrix.dataset }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          sanityApiToken: ${{ secrets.SANITY_API_TOKEN }}
          sanityPreviewSecret: ${{ secrets.SANITY_STUDIO_PREVIEW_SECRET }}
          algoliaAppId: ${{ secrets.ALGOLIA_APP_ID }}
          algoliaApiKey: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          archiveContentLink: ${{ vars.ARCHIVE_CONTENT_LINK }}
          friendlyCaptchaSitekey: ${{ matrix.dataset == 'brazil' && vars.BRAZIL_FC_SITEKEY || vars.GLOBAL_FC_SITEKEY }}
          friendlyCaptchaPuzzleEndpoint: ${{ matrix.dataset == 'brazil' && vars.BRAZIL_FC_PUZZLE_END_POINT || vars.GLOBAL_FC_PUZZLE_END_POINT }}
          environment: ${{ secrets.ENV }}

      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
