//Keep these colors in sync with correspondent tailwind config colors
export const defaultColors = [
  {
    title: 'White',
    value: 'hsl(0, 0%, 100%)',
    key: 'white-100',
    dark: false,
  },
  {
    title: 'Moss Green Light',
    value: 'hsl(184, 30%, 96%)',
    key: 'moss-green-50',
    dark: false,
  },
  {
    title: 'Spruce Wood',
    value: 'hsl(25, 100%, 94%)',
    key: 'spruce-wood-90',
    dark: false,
  },
  { title: 'Mist Blue', value: 'hsl(199, 58%, 90%)', key: 'mist-blue-100', dark: false },
  { title: 'Mid Yellow', value: '#fff5b8', key: 'yellow-50', dark: false },
  { title: 'Mid Orange', value: '#f8d1af', key: 'orange-50', dark: false },
  { title: 'Mid Blue', value: '#49709c', key: 'blue-50', dark: true },
  { title: 'Mid Green', value: '#c3e4ce', key: 'green-50', dark: false },
  { title: 'Energy Red', value: 'hsl(348, 100%, 54%)', key: 'energy-red-50', dark: false, onlyTextColor: true },
  { title: 'Black', value: 'rgba(61, 61, 61, 1)', key: 'slate-80', dark: false, onlyTextColor: true },
  { title: 'Sand', value: '#FFE7D6', key: 'sand-and-summer-50', dark: false },
  { title: 'Light green', value: '#E6FAEC', key: 'norwegian-woods-40', dark: false },
  {
    title: 'Moss Green 60',
    value: 'hsl(184, 31%, 89%)',
    key: 'moss-green-60',
    dark: false,
  },
  {
    title: 'North Sea 50',
    value: '#A8C3DB',
    key: 'north-sea-50',
    dark: false,
  },
  {
    title: 'North Sea 40',
    value: '#DFF5FF',
    key: 'north-sea-40',
    dark: false,
  },
  {
    title: 'Autumn Storm 60',
    value: '#86A7AC',
    key: 'autumn-storm-60',
    dark: false,
  },
  {
    title: 'Autumn Storm 40',
    value: '#C2D4D6',
    key: 'autumn-storm-40',
    dark: false,
  },
  {
    title: 'Grey 50',
    value: 'hsl(0, 0%, 55%)',
    key: 'grey-50',
    dark: false,
  },
  {
    title: 'Grey 10',
    value: 'hsl(0, 0%, 97%)',
    key: 'grey-10',
    dark: false,
  },
]
